name: Daily API Call

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: update all tasks
        run: |
          curl -X GET https://cleanr-back.onrender.com/tasks/updateAllTasks
